.PHONY: clean All

All:
	@echo "----------Building project:[ cfq_ipctrain - Debug ]----------"
	@cd "cfq_ipctrain" && "$(MAKE)" -f  "cfq_ipctrain.mk"
clean:
	@echo "----------Cleaning project:[ cfq_ipctrain - Debug ]----------"
	@cd "cfq_ipctrain" && "$(MAKE)" -f  "cfq_ipctrain.mk" clean
